const cars = [
  {
    id: 1,
    name: "Hyundai i20",
    modelName: "i20 Sportz",
    yearsUsed: 3,
    price: "8 Lakhs",
    fuelType: "Petrol",
    engine: "1.2L Kappa",
    description: "Compact premium hatchback with a smooth ride and sporty design.",
    image: "https://static.toiimg.com/thumb/imgsize-23456,msid-78782048,width-600,resizemode-4/hyundai-i20-n-front.jpg",
    stock: 5,
  },
  {
    id: 2,
    name: "Suzuki Swift",
    modelName: "Swift VXi",
    yearsUsed: 2,
    price: "7.5 Lakhs",
    fuelType: "Petrol",
    engine: "1.2L DualJet",
    description: "Popular hatchback with excellent fuel efficiency and low maintenance.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTULdst3M5F5AGl09gIfqv_nWmo9xt4WmVI4A&s",
    stock: 5,
  },
  {
    id: 3,
    name: "Tata Nexon",
    modelName: "Nexon XM",
    yearsUsed: 4,
    price: "10 Lakhs",
    fuelType: "Diesel",
    engine: "1.5L Revotorq",
    description: "Compact SUV with strong build quality and top-notch safety ratings.",
    image: "https://imgd.aeplcdn.com/664x374/n/cw/ec/141867/nexon-facelift-exterior-left-rear-three-quarter.jpeg?isig=0&q=80",
    stock: 5,
  },
  {
    id: 4,
    name: "Hyundai Verna",
    modelName: "Verna SX",
    yearsUsed: 2,
    price: "20 Lakhs",
    fuelType: "Petrol",
    engine: "1.5L Turbo GDi",
    description: "Premium sedan with luxurious interiors and advanced tech features.",
    image: "https://gaadiwaadi.com/wp-content/uploads/2023/05/2023-hyundai-verna-1.jpg",
    stock: 5,
  },
  {
    id: 5,
    name: "Skoda Slavia",
    modelName: "Slavia Style",
    yearsUsed: 1,
    price: "18 Lakhs",
    fuelType: "Petrol",
    engine: "1.0L TSI",
    description: "Stylish and modern sedan with European design and comfort.",
    image: "https://lh6.googleusercontent.com/proxy/AsSUMZlTTv1OrBeSvNik7HyHJh-eAyXkmRB-_FV1bg2wVKARj-blNIaCrTRyiKw6EHPLaKLD3XyS3Zsz1u9eky3FIuWDTJTxhlM",
    stock: 5,
  },
  {
    id: 6,
    name: "Volkswagen Virtus",
    modelName: "Virtus Highline",
    yearsUsed: 1,
    price: "21 Lakhs",
    fuelType: "Petrol",
    engine: "1.0L TSI",
    description: "Premium German sedan with responsive handling and elegant design.",
    image: "https://img.autocarindia.com/Galleries/20220308030907_Virtus_2022%20_1_.jpg",
    stock: 5,
  },
  {
    id: 7,
    name: "Mahindra BE6E",
    modelName: "BE6E Electric",
    yearsUsed: 0,
    price: "20 Lakhs",
    fuelType: "Electric",
    engine: "EV Motor",
    description: "Upcoming futuristic electric SUV with cutting-edge tech and bold styling.",
    image: "https://motoringworld.in/wp-content/uploads/2024/11/BE6E-258-scaled.jpg",
    stock: 5,
  },
  {
    id: 8,
    name: "Mahindra XUV700",
    modelName: "XUV700 AX7",
    yearsUsed: 1,
    price: "30 Lakhs",
    fuelType: "Diesel",
    engine: "2.2L mHawk",
    description: "Feature-loaded SUV with ADAS, panoramic sunroof and powerful performance.",
    image: "https://www.motorbeam.com/wp-content/uploads/Mahindra-XUV700-Blaze-Edition.jpg",
    stock: 5,
  },
  {
    id: 9,
    name: "Kia Seltos",
    modelName: "Seltos GTX+",
    yearsUsed: 2,
    price: "17 Lakhs",
    fuelType: "Petrol",
    engine: "1.4L Turbo GDi",
    description: "Trendy urban SUV with premium features and a refined drive experience.",
    image: "https://stimg.cardekho.com/images/carexteriorimages/930x620/Kia/Seltos-2023/8709/1688465684023/front-left-side-47.jpg",
    stock: 5,
  },
  {
    id: 10,
    name: "Toyota Fortuner",
    modelName: "Fortuner Legender",
    yearsUsed: 3,
    price: "35 Lakhs",
    fuelType: "Diesel",
    engine: "2.8L GD",
    description: "Premium SUV known for rugged reliability, performance, and road presence.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_2aQrnO7mzQKq2Mh1qClmies61YjlWOnFrw&s",
    stock: 5,
  },
  {
    id: 11,
    name: "Honda City",
    modelName: "City ZX",
    yearsUsed: 2,
    price: "13 Lakhs",
    fuelType: "Petrol",
    engine: "1.5L i-VTEC",
    description: "Iconic mid-size sedan with refined engine and smooth driving dynamics.",
    image: "https://media.assettype.com/evoindia/2022-05/3d2693d5-6d85-4a47-a0fd-a1a1352b1579/Photo_27_04_22__8_01_15_PM.jpg",
    stock: 5,
  },
  {
    id: 12,
    name: "MG Hector",
    modelName: "Hector Sharp",
    yearsUsed: 2,
    price: "18 Lakhs",
    fuelType: "Petrol",
    engine: "1.5L Turbo",
    description: "Connected SUV with voice commands, large infotainment screen and comfort.",
    image: "https://resize.indiatvnews.com/en/resize/newbucket/1200_-/2019/06/hector-exteriors-4-770x433-1561623814.jpg",
    stock: 5,
  },
  {
    id: 13,
    name: "Renault Kwid",
    modelName: "Kwid Climber",
    yearsUsed: 3,
    price: "5 Lakhs",
    fuelType: "Petrol",
    engine: "1.0L SCe",
    description: "Compact city hatchback with SUV-like styling and affordable pricing.",
    image: "https://upload.wikimedia.org/wikipedia/commons/7/77/2023_Renault_Kwid_Iconic_%28Colombia%29_front_view_01.png",
    stock: 5,
  },
  {
    id: 14,
    name: "Ford EcoSport",
    price: "9.5 Lakhs",
    image: "https://www.carandbike.com/_next/image?url=https%3A%2F%2Fimages.carandbike.com%2Fcar-images%2Fgallery%2Fford%2Fecosport%2Fexterior%2Fford-ecosport-style.jpg%3Fv%3D2021-02-24&w=640&q=75",
    modelName: "EcoSport Titanium",
    yearsUsed: 3,
    engine: "1.5L Petrol",
    fuelType: "Petrol",
    description: "Compact SUV with great mileage, perfect for city and long drives.",
    stock: 5,
  },
  {
    id: 15,
    name: "Nissan Magnite",
    price: "8.9 Lakhs",
    image: "https://ik.imagekit.io/girnar/sayaratbay/large/gallery/exterior/30/2125/nissan-magnite-front-angle-low-view-897947.jpg",
    modelName: "Magnite XV Turbo",
    yearsUsed: 2,
    engine: "1.0L Turbo",
    fuelType: "Petrol",
    description: "Stylish, affordable SUV with advanced safety features and great comfort.",
    stock: 5,
  },
  {
    id: 16,
    name: "Renault Duster",
    price: "11.5 Lakhs",
    image: "https://media.istockphoto.com/id/1388343451/photo/renault-duster.jpg?s=612x612&w=0&k=20&c=JiR3B07NezedmNhRVgo_mJvq9ZjLHaJsItiaNiJlVUM=",
    modelName: "Duster RXZ",
    yearsUsed: 4,
    engine: "1.5L Diesel",
    fuelType: "Diesel",
    description: "Sturdy build, strong performance, ideal for rough terrains and long drives.",
    stock: 5,
  },
  {
    id: 17,
    name: "Audi A6",
    modelName: "A6 Technology",
    yearsUsed: 1,
    price: "55 Lakhs",
    fuelType: "Petrol",
    engine: "2.0L TFSI",
    description: "Luxury sedan with cutting-edge technology, plush interiors, and dynamic performance.",
    image: "https://spn-sta.spinny.com/blog/20230612165825/Audi-A6.webp?compress=true&quality=80&w=1024&dpr=2.6",
    stock: 5,
  },
  {
    id: 18,
    name: "BMW X5",
    modelName: "X5 xDrive30d",
    yearsUsed: 2,
    price: "85 Lakhs",
    fuelType: "Diesel",
    engine: "3.0L Turbo",
    description: "Premium luxury SUV offering exceptional comfort, power, and technology.",
    image: "https://hips.hearstapps.com/hmg-prod/images/2024-bmw-x5-m60i-102-6602d48787fb7.jpg?crop=0.772xw:0.651xh;0.0897xw,0.171xh&resize=1200:*",
    stock: 5,
  },
  {
    id: 19,
    name: "Mercedes-Benz C-Class",
    modelName: "C 300d",
    yearsUsed: 1,
    price: "70 Lakhs",
    fuelType: "Diesel",
    engine: "2.0L Turbo",
    description: "Sophisticated sedan combining luxury, performance, and advanced tech features.",
    image: "https://www.topgear.com/sites/default/files/2021/11/Mercedes_C300D_0000.jpg",
    stock: 5,
  },
  {
    id: 20,
    name: "Toyota Land Cruiser",
    modelName: "Land Cruiser 300",
    yearsUsed: 3,
    price: "1.2 Crores",
    fuelType: "Diesel",
    engine: "3.3L Twin-Turbo V6",
    description: "Legendary off-road vehicle with exceptional reliability and power.",
    image: "https://acko-cms.ackoassets.com/Toyota_Land_Cruiser_4192ce25f5.png",
    stock: 5,
  },
  {
    id: 21,
    name: "Lexus RX",
    modelName: "RX 500h",
    yearsUsed: 1,
    price: "1.1 Crores",
    fuelType: "Hybrid",
    engine: "2.5L Hybrid",
    description: "Premium hybrid SUV offering a luxurious driving experience with eco-friendly performance.",
    image: "https://npr.brightspotcdn.com/9d/d6/9d97833e433a8ded3b326efa883d/lexus-rx-right-front.jpg",
    stock: 5,
  },
  {
    id: 22,
    name: "Porsche 911",
    modelName: "911 Carrera",
    yearsUsed: 2,
    price: "1.5 Crores",
    fuelType: "Petrol",
    engine: "3.0L Turbo",
    description: "Iconic sports car with dynamic performance and timeless design.",
    image: "https://c.ndtvimg.com/2024-05/9j043eng_2025-porsche-911-carrera-gts-launched_625x300_30_May_24.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=738",
    stock: 5,
  }
];

export default cars;
